name: Domain Monitor

on:
  schedule:
    # 1h sáng VN (UTC+7 = 18h hôm trước UTC)
    - cron: "0 18 * * *"
    # 12h trưa VN (UTC+7 = 5h UTC)
    - cron: "0 5 * * *"
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # cần quyền để push lên gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-whois beautifulsoup4 lxml

      - name: Run monitor script
        run: python monitor.py
